name: pearl
channels:
  - defaults
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - _r-mutex=1.0.1
  - _tflow_select=2.3.0
  - absl-py=1.0.0
  - astor=0.8.1
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - black=22.6.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cctools_osx-64=973.0.1
  - certifi=2022.12.7
  - clang=12.0.1
  - clang-12=12.0.1
  - clang_osx-64=12.0.1
  - clangxx=12.0.1
  - clangxx_osx-64=12.0.1
  - click=8.0.4
  - compiler-rt=12.0.1
  - compiler-rt_osx-64=12.0.1
  - curl=7.80.0
  - cycler=0.11.0
  - dataclasses=0.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gast=0.2.2
  - gettext=0.19.8.1
  - gfortran_impl_osx-64=9.3.0
  - gfortran_osx-64=9.3.0
  - gmp=6.2.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.42.0
  - gsl=2.6
  - h5py=3.6.0
  - harfbuzz=3.0.0
  - hdf5=1.12.1
  - icu=68.2
  - importlib-metadata=4.8.2
  - isl=0.22.1
  - isort=5.9.3
  - jbig=2.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld64_osx-64=609
  - ldid=2.1.2
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp12=12.0.1
  - libcurl=7.80.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm12=12.0.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxgboost=1.3.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lightgbm=3.1.1
  - llvm-openmp=12.0.1
  - llvm-tools=12.0.1
  - lz4-c=1.9.3
  - make=4.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mpc=1.2.1
  - mpfr=4.1.0
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.2.4
  - pango=1.48.10
  - pathspec=0.10.3
  - patsy=0.5.3
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - platformdirs=2.5.2
  - protobuf=3.19.1
  - py-xgboost=1.3.3
  - pyparsing=3.0.6
  - python=3.7.7
  - python-dateutil=2.8.2
  - python-tzdata=2021.5
  - python_abi=3.7
  - pytz=2021.3
  - pytz-deprecation-shim=0.1.0.post0
  - r=3.6
  - r-assertthat=0.2.1
  - r-base=3.6.3
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-blob=1.2.1
  - r-boot=1.3_28
  - r-cachem=1.0.5
  - r-class=7.3_19
  - r-cli=2.5.0
  - r-cluster=2.1.2
  - r-codetools=0.2_18
  - r-crayon=1.4.1
  - r-dbi=1.1.1
  - r-dbplyr=2.1.1
  - r-dicekriging=1.6.0
  - r-dplyr=1.0.6
  - r-ellipsis=0.3.2
  - r-fansi=0.4.2
  - r-fastmap=1.1.0
  - r-foreign=0.8_76
  - r-generics=0.1.0
  - r-glue=1.4.2
  - r-grf=1.2.0
  - r-kernsmooth=2.23_20
  - r-lattice=0.20_44
  - r-lifecycle=1.0.0
  - r-lmtest=0.9_38
  - r-magrittr=2.0.1
  - r-mass=7.3_54
  - r-matrix=1.3_3
  - r-memoise=2.0.0
  - r-mgcv=1.8_35
  - r-nlme=3.1_152
  - r-nnet=7.3_16
  - r-pillar=1.6.1
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-purrr=0.3.4
  - r-r6=2.5.0
  - r-rcpp=1.0.6
  - r-rcppeigen=0.3.3.9.1
  - r-recommended=3.6
  - r-rlang=0.4.11
  - r-rpart=4.1_15
  - r-rsqlite=2.2.5
  - r-sandwich=3.0_1
  - r-spatial=7.3_14
  - r-survival=3.2_10
  - r-tibble=3.1.2
  - r-tidyselect=1.1.1
  - r-utf8=1.2.1
  - r-vctrs=0.3.8
  - r-withr=2.4.2
  - r-zoo=1.8_9
  - readline=8.1
  - rpy2=2.9.4
  - scikit-learn=0.24.2
  - scipy=1.7.3
  - setuptools=59.4.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sqlite=3.37.0
  - statsmodels=0.13.5
  - tabulate=0.8.10
  - tapi=1100.0.11
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tktable=2.10
  - tomli=2.0.1
  - tornado=6.1
  - typed-ast=1.4.3
  - typing_extensions=4.0.1
  - tzdata=2021e
  - tzlocal=4.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - wrapt=1.13.3
  - xgboost=1.3.3
  - xz=5.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
variables:
  TF_CPP_MIN_LOG_LEVEL: 3
  PYTHONHASHSEED: 0
